### ISSUE TITLE
Intermediate section: command-line git

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#107]
This issue tracks the command line version control section. This issue tracks the testing section in the intermediate material.

This issue can be closed when

- [ ] There are an initial set of exercises corresponding to the outline of the material (which may evolve as part of this task)
- [ ]  There is a first draft of the text of the section in the intermediate material.

**Comment by DamienIrving** [comment]
See #164

**Comment by DamienIrving** [comment]
A number of people have extended/modified the existing Software Carpentry git lessons:  
https://uw-madison-datascience.github.io/git-novice-custom/  
https://m4rkd.github.io/git-beyond-the-basics/  
https://dlstrong.github.io/git-novice/

**Comment by DamienIrving** [comment]
@ChristinaLK For the introduction to the command line git lessons, I need to explain why someone might want to use git at the command line rather than via any of the GUI clients out there. I've never used a git GUI client, so I was hoping you might be able to list a few reasons? 

Obviously one reason is if you're working on a remote system (e.g. a supercomputing facility) they probably won't have a GUI client installed (and you may only have terminal access to the system), but are there things you can do command line that you can't do with the GUIs? From my quick look, GitKraken looks like it has pretty extensive functionality...

**Comment by joelostblom** [comment]
@DamienIrving In case it is useful, there are [a few comments here](https://www.slant.co/versus/1501/13489/~the-command-line_vs_gitkraken) if you scroll down to the "cons" section. For example, not open source, not free for private repos, missing hard reset and interactive rebase, some features being only in the pro version. I don't know how accurate these are, I don't use Git Kraken myself either. (Potential for automation might be worth mentioning also)

**Comment by DamienIrving** [comment]
We also need to decide how much of the branching workflow information (see #147) needs to be included. I'm thinking that rebasing is possibly too much information, but the other content in `branches.Rmd` on pull requests and "what is a feature" is valuable.

**Comment by ChristinaLK** [comment]
@DamienIrving I'm sorry I'm just seeing this. 

GitKraken doesn't let you bespoke-edit file conflicts, so that's one possible deal-breaker. 

I think the main arguments I'd make for/against command line are how well it integrates with your workflow (it's handy if you already have a command window open to test scripts) and the good old "typing is faster than clicking". I think the remote access argument (e.g. working on a supercomputer)  is also a good one.
