### ISSUE TITLE
Good examples and data sets

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#14]
Please add notes to this issue pointing at good data sets and/or describing good examples or exercises that you would like to see in the lessons (at any level).

**Comment by ChristinaLK** [comment]
One of my local colleagues did a Python plotting lesson on CO2 data measured from Mauna Loa, showing both the annual flux of carbon in the atmosphere and the trend of rising carbon over time. 

His repository is here: https://github.com/megarcia/SWC_Python

**Comment by DamienIrving** [comment]
@ChristinaLK We could possibly make the CO2 analysis story a little more interesting by looking at data from all three of the Premier Global Baseline Stations:
* [Mauna Loa, Hawaii, USA](http://scrippsco2.ucsd.edu/data/atmospheric_co2/primary_mlo_co2_record)
* [Cape Grim, Tasmania, Australia](https://www.csiro.au/en/Research/OandA/Areas/Assessing-our-climate/Latest-greenhouse-gas-data)
* [Alert, Nunavut, Canada](https://cdiac.ess-dive.lbl.gov/trends/co2/csiro/csiro-alt.html)

The cool thing being that because of the long residence time of greenhouse gases in the atmosphere (~100 years), they are more or less uniformly distributed around the globe and you get a similar result no matter where you measure from (provided your sample isn't contaminated by nearby emission sources, which is why the premier stations are in remote places). There is more vegetation in the Northern Hemisphere (which is responsible for the annual cycle you mention of the planet essentially breathing out during boreal autumn and in during boreal spring), so there will be some subtle differences between the monthly Cape Grim timeseries and the Alert / Mauna Loa timeseries that we could draw out during the lessons.

I guess the only potential downside is that the data won't require much cleaning up. There would be some work involved in merging the raw data files from all three sites into a consistent format and there are missing values for some months early in the record, but that's about it as far as cleaning goes.

**Comment by gvwilson** [comment]
I think our learners will thank us if we show them how to manipulate clean data first and only then dive into the messiness of reality :-) The climate data would be very cool.

**Comment by mbonsma** [comment]
@joelostblom mentioned this I believe, but here's what I found when I searched 'AirBnB data': http://insideairbnb.com/get-the-data.html. As far as I understand, it's a collection of publicly available listing data scraped from AirBnB's website. Here's a [visualization from the website for Toronto](http://insideairbnb.com/toronto/), for example.

**Pros:** 
- data is interesting and relevant to people from many disciplines
- data is updated regularly - very current research is possible
- past data is available - analysis over time is possible
- exercises can be formulated with one city's data, but instructors can easily substitute local examples
- data is available under CC-1.0.

**Cons:**
- it's not affiliated with AirBnB - someone should probably pick through the [disclaimers](http://insideairbnb.com/about.html#disclaimers) and make sure there wouldn't be any legal or privacy issues.

**Comment by cwickham** [comment]
In a similar vein to the CO2 data I've adapted parts of a chapter on "Revealing Change" in Alberto Cairo's "Truthful Art: data, charts and maps for communication" to US employment data.

I say similar to the CO2 data, since it's also a time series where the salient features include trend, seasonal patterns, and noise.  

What I love about the chapter is that the motivation is entirely on getting as accurate an understanding of the variation over time as possible (motivated by a misleading plot), but the process of doing so concretely demonstrates the power of combining small data manipulation steps with visualization. 

As some examples of the range of tasks involved (from simple to complex):
* putting population measured in thousands of people and employed measured in millions on the same scale
* finding the ratio of employed to working population and expressing as a percentage
* summarizing by month to examine the average seasonal pattern
* finding differences from the average seasonal pattern to reveal unusual values (that are obscured by seasonal variation)

Cairo's works through Spanish data on Social Security enrollment and the Spanish population between 16-64.  In class, I've used the closest US equivalents I could find:

* *U.S. Bureau of Labor Statistics, All Employees: Total Nonfarm Payrolls* [PAYNSA](https://fred.stlouisfed.org/series/PAYNSA) and,

* *Organization for Economic Co-operation and Development, Working Age Population: Aged 15-64: All Persons for the United States* [LFWA64TTUSM647N](https://fred.stlouisfed.org/series/LFWA64TTUSM647N)

**Comment by cwickham** [comment]
I've also found replicating graphics from data in the [fivethirtyeight R package](https://fivethirtyeight-r.netlify.com/) to be a fun way to motivate practice with data manipulation and visualization.

For example, I've used this [case study](https://github.com/cwickham/data-science-in-tidyverse-solutions/blob/master/04-Case-Study-solutions.md) after covering ggplot2, dplyr and tidyr

**Comment by lwjohnst86** [comment]
As per #126 and our last meeting, closing this for now.
