### ISSUE TITLE
Revise code style and review

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#149]
Revise `style.Rmd`:

* Exercises
* R components?
* Add section on review

**Comment by joelostblom** [comment]
A few comments on the current `style.Rmd` to consider when revising.

- l.56 Mention that a single press of tab can be configured to insert 4 spaces
  in most (all?) IDEs (and this is often the default behavior even). I have
  realized that people can be against spaces because they. don't want to press
  space bar several times.
- l.68 Change to constants/global variables for clarity?
- l.139 Mention that there is a linter built into Spyder.
- l.627: This is also the [first section in
  PEP8](https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds),  memorably expressed as "A Foolish Consistency is the Hobgoblin of Little
  Minds". Could be amusing to include.

**Comment by DamienIrving** [comment]
In the [27 August meeting](https://github.com/merely-useful/merely-useful.github.io/wiki/Meeting-agenda-2019-08-27) we chatted about the code style and review material and decided it is probably best located in the novice lessons (perhaps alongside the refactoring #159 content). Pretty much all the content relates to Python, so I've changed the label to novice Python.

cc @brandeism @ChristinaLK @mbonsma @joelostblom

**Comment by lwjohnst86** [comment]
@SaraMati take material from `r-reproducibility.Rmd` file for the styling and revise it for the Python material. Maybe put it in `py-reproducibility.Rmd`?

**Comment by gvwilson** [comment]
See #351.
