### ISSUE TITLE
Discussion: Should we have a visual indicator/separate section for good to know tips?

### ISSUE THREAD

**Issue by joelostblom** [merely-useful/merely-useful.github.io#174]
When I was writing the py dev section, I found this quite handy for things that were good to know, but maybe more advanced, or not necessary knowledge. It could be nicely styled div, similar to the bootstrap info divs.

Example of what would go into one of these:

> Note: You will sometimes hear packages refers to as "modules". The two
> words are often used interchangeably. Technically, a package is a folder that
> contains modules (scripts), which in turn contains functions (code).

**Comment by lwjohnst86** [comment]
Two things:

- I think we should worry about special formatting later in the development stage, when we have much more material completed. If anyone is interested in adding these, maybe add a TODO item near the text identifying it as a "good to know".
- The really tricky part about trying to implement this is that it will show up on the html version, but (as far as I know) not the PDF nor epub versions. That I know of, conversion to pdf through LaTeX via pandoc drops those special div tags so that means we'd have to write a hook for pandoc or create a special TeX tag whenever div tags are used. I feel that's too much work for the potentially few instances of using it. Unless someone knows it already, it means someone would have to spend the time learning how to do it rather than doing other work on this project.

I generally think that these good to know tips work fine as simple text and as they flow through the material.

But these are just my own thoughts :relaxed:

**Comment by joelostblom** [comment]
Thanks @lwjohnst86, I agree with the points you bring up. I should have phrased myself more carefully to get to the center of the issue: *Should we bring up slightly more advanced / good-to-know-but-not-necessary information in the text or in a separate section/div/quote.*

> I generally think that these good to know tips work fine as simple text and as they flow through the material.

I prefer to have some sort of visual indicator for these because I think it facilitates retention to anchor information to different visual elements and breaks up the text into chunks which facilitates reading and page orientation for the learner (this is my personal experience).

One example of this strategy can be seen on [this page](https://docs.microsoft.com/en-us/visualstudio/python/overview-of-python-tools-for-visual-studio?view=vs-2019). They use purple divs but as mentioned above we can use something simpler like a quote.

**Comment by joelostblom** [comment]
Me and @lwjohnst86 discussed this briefly in the py-dev PR. I am going to close this issue quoting what I said in the PR discussion since I think it is unnecessary to complicate the writing process:

> [This seems promising](https://stackoverflow.com/questions/47253228/how-to-a-scenebreak-in-bookdown/47294235#47294235) to me, what do you think? We could create a function for "Advanced notes/Deep dives" (and maybe also "Exercises" if we want that to be more than a standard heading) that authors could call when inserting a similar paragraph as mine here.

> Although this now appears technically feasible, and I like having a visually distinct element for advanced notes, it appears I am the only one who has written in this style so far (the rest follow your previous suggestion of having everything in paragraphs. So I am inclined to wander down the path of least resistance here and change my writing instead of encouraging everyone else to alter theirs.
