### ISSUE TITLE
Cover $PATH in rse-bash?

### ISSUE THREAD

**Issue by ljdursi** [merely-useful/merely-useful.github.io#178]
The current PR for python packaging ( #117 ) includes a backwards reference to rse-bash for possible discussion of search paths in the context of explaining Python environments and virtualenv

This issue can be closed when either:
- [ ] The Bash lesson includes discussion of search path, and
- [ ] The python packaging lesson is updated to refer to that discussion,

**or**:

- [ ] It's decided the Bash lesson will not include such discussion
- [ ] The python packaging lesson is updated to be self contained

**Comment by DamienIrving** [comment]
In the [meeting on 14 August](https://github.com/merely-useful/merely-useful.github.io/wiki/Meeting-agenda-2019-08-14) we decided that `$PATH` should be introduced in the rse-bash lessons after we introduce bash scripts. In other words, we could put the script we write into a directory for our own personal utilities, which we add to our `$PATH` via an update to `bash_profile` so that it can be run anywhere. We could also introduce at this point other tips about using `bash_profile`, such as an update to the appearance of the command line prompt. 

I'll will add this content to the rse-bash lesson soon.

**Comment by ChristinaLK** [comment]
I'm happy to review the PR and/or add text after there's a placeholder.

**Comment by gvwilson** [comment]
I will add a section on PATH once the current `rse-bash.Rmd` is merged - thanks.
