### ISSUE TITLE
Discussion: Spyder not funded by Anaconda

### ISSUE THREAD

**Issue by mbonsma** [merely-useful/merely-useful.github.io#185]
I came across a [status update from Spyder](https://github.com/spyder-ide/spyder/wiki/Current-Funding-and-Development-Status) in 2017 that Anaconda had stopped funding its development. This doesn't mean that it will stop being developed, it just means that the pace has slowed considerably and that they're no longer focusing on extra features - for instance, spyder-notebooks and spyder-reports that might have come in handy for our publishing section. 

**My question:** If this is news to people, is this a reason to revisit our tool choice for the Python IDE?

**Comment by joelostblom** [comment]
I've also been thinking about this and it's worth discussing in my opinion.
It's front and center in their Readme so I would say that at least it's
discouraging for new users to find out the tool they just learnt is in
maintenence mode. Of course many if the principles carry over to other
tools, but worth thinking and talking more about.

**Comment by SaraMati** [comment]
They are integrating Anaconda with PyCharm:
https://www.anaconda.com/anaconda-2019-03-release/
and JetBrains have released [Pycharm with Anaconda plugins](https://www.jetbrains.com/pycharm/promo/anaconda/?_ga=2.36714720.1330486491.1566267837-1220241616.1566267837)  for now. 

If the group decides to change to Pycharm, I can modify the py-getting-started section. At the current version, the changes would be minimal, since the instructions are merely for differentiating the console and the script panes. So, the edits would be limited to 
line 90: "move to the left pane" to "open a new file"; or 
in line 16: "top right pane" to "Help pane in the top toolbar".

**Comment by lwjohnst86** [comment]
Discussion is here as a record, closing for now.
