### ISSUE TITLE
Integrate the Zipf's Law narrative into correctness and CI chapters

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/merely-useful.github.io#372]
One section of the book where the Zipf's Law narrative is yet to be included is the chapters about testing. [narrative.md](https://github.com/merely-useful/merely-useful.github.io/blob/book/py-rse/narrative.md) suggests the following updates: 

**Chapter 14: Correctness**
This chapter introduces testing and needs to be updated to write tests for the Zipf's Law code. For example, `countwords.py` could be tested using an input text file where the count for each word is already known, and `plotcounts.py` could be given an input csv file where the alpha value in our line fitting algorithm is exactly 1 (i.e. perfect conformity to Zipf's Law).

**Chapter 15: Continuous integration**
This chapter needs to be updated so the tests developed in the previous chapter are implemented using Travis CI.

**Comment by DamienIrving** [comment]
@cwickham We talk about the alpha parameter in the advanced git chapter as follows:
> "The most frequent word will occur approximately \(2^\alpha\) times as often as the second most frequent word, \(3^\alpha\) times as often as the third most frequent word, and so on."

Based on that understanding of alpha, my test for our calculation of alpha (which I'm looking to add to the correctness chapter) currently looks as follows:

```
import numpy as np
import plotcounts

def test_alpha():
    """Test the calculation of the alpha parameter."""
       
    word_counts = np.array([60, 30, 20, 15, 12, 10])
    alpha = plotcounts.get_power_law_params(word_counts)
    assert alpha == 1.0
```

The problem is that alpha = 3.03 in this example. I'm confused 😕

**Comment by cwickham** [comment]
@DamienIrving, the problem is that the values you generated are consistent with the empirical law:
> "The most frequent word will occur approximately (2^\alpha) times as often as the second most frequent word, (3^\alpha) times as often as the third most frequent word, and so on."

but not statistical model that the maximum likelihood estimates are based on.  So, for instance, if alpha = 1, and the maximum word frequency is 60, we would expect to see a number of words with frequencies below 10.  How many exactly?  Well, that's complicated because the statistical model we are using (after Moreno et al), only has the behavior of the empirical law "in the tails" - Moreno's terminology, which means for large word frequencies.  

One way to get data consistent with the statistical model is to use the model to generate a set of word frequencies that are equally likely.  By adding the constraint that the maximum frequency is 60, I get (sorry about the R code):
```r
word_counts <- c(60, 30, 20, 15, 12, 10, 8, 7, 6, 6, 5, 4, 4, 4, 4, 3, 3, 3, 3,
  3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1,
  1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
```

For me, in R, this gets me much closer to alpha = 1
``` r
nlog_likelihood <- function(beta, x){
  - sum(log((1/x)^(beta - 1) - (1/(x + 1))^(beta - 1)))
}

mle <- function(x){
  beta <- optim(1, nlog_likelihood, x = x,
    lower = 1, upper = 4,
    hessian = TRUE, method = "Brent")$par
  list(beta = beta, alpha = 1/(beta - 1))
}

mle(word_counts)
#> $beta
#> [1] 2.03692
#> 
#> $alpha
#> [1] 0.9643945
```

There's still two reasons why this won't get us exactly 1.0:
* The probabilities involved are not simple fractions, and given we need a finite number of unique words, our distribution deviates a little from the ideal because of rounding.
* For large sample sizes (in this case, a large number of unique words), maximum likelihood estimates are asymptotically unbiased (the estimate, on average, will be the true value), but there are no guarantees for any fixed sample size.  So, even if we could generate "perfect" test data, the estimate may not be exactly 1.0, although we would expect it to get closer (on average) with larger sample sizes.

Both of these problems should get better with larger sample sizes, using the same method for generating `word_counts` above but now bumping up the maximum frequency to 600, 
``` r
inverse_ccdf <- function(x, beta){
  x^(1/(1 - beta))
}
ccdf <- function(x, beta){
  x ^ ( 1 - beta)
}
max_freq <- 600
beta <- 2
word_counts_larger <- inverse_ccdf(
  seq(ccdf(max_freq, beta = beta), 1, length.out = max_freq),
  beta = beta)
word_counts_larger <- floor(word_counts_larger)
mle(word_counts_larger)
#> $beta
#> [1] 2.004871
#> 
#> $alpha
#> [1] 0.9951525
```
Does indeed get closer, which is reassuring, but `word_counts_larger` is now ten times as big.
<details>
 <summary>For reference: word_counts_larger</summary>
word_counts_larger <- c(600, 300, 200, 150, 120, 100, 85, 75, 66, 60, 54, 50, 46, 42, 
40, 37, 35, 33, 31, 30, 28, 27, 26, 25, 24, 23, 22, 21, 20, 20, 
19, 18, 18, 17, 17, 16, 16, 15, 15, 15, 14, 14, 13, 13, 13, 13, 
12, 12, 12, 12, 11, 11, 11, 11, 10, 10, 10, 10, 10, 10, 9, 9, 
9, 9, 9, 9, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 7, 7, 7, 7, 7, 7, 7, 
7, 7, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 5, 5, 5, 
5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 
4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 
3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 
2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 
1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1)
</details>

In terms of the chapter, I'm not sure what to advise.  This is a common problem in statistical computing, where we know what kind of behavior we should expect in some limit, or "on average", but there isn't necessarily a single test case that can easily be automated.

**Comment by DamienIrving** [comment]
Thanks, @cwickham. That makes sense.

In the correctness chapter the idea of generating test data (called the "fixture") is introduced, so we can generate synthetic word count data like you've done for `word_counts_larger`. The idea of requiring the result to be approximately equal to an expected value (within some absolute or relative tolerance) is also introduced, so this is a great application of that principle.

Here's my new test function,
```
import pytest
import numpy as np
import plotcounts

def test_alpha():
    """Test the calculation of the alpha parameter."""
    max_freq = 600
    word_counts = np.floor(max_freq / np.arange(1, max_freq + 1))
    alpha = plotcounts.get_power_law_params(word_counts)
    assert alpha == pytest.approx(1.0, abs=0.01)
```
which passes with flying colors:
```
$ pytest 
============================= test session starts ==============================
platform darwin -- Python 3.7.6, pytest-5.4.1, py-1.8.1, pluggy-0.12.0
rootdir: /Users/z3526123/Documents/volunteer/merely-useful.github.io/zipfs-law/bin
collected 1 item                                                               

test_counts.py .                                                         [100%]

============================== 1 passed in 0.49s ===============================
```

**Comment by DamienIrving** [comment]
Project structure for @k8hertweck...

Where should my script full of tests (`test_zipfs.py`) live?
- `/Users/amira/zipf/bin`
- `/Users/amira/zipf/bin/tests`
- `/Users/amira/zipf/tests`

**Comment by k8hertweck** [comment]
@DamienIrving I am uncertain about this; my gut says `/Users/amira/zipf/tests` but @joelostblom may be able to advise with more certainty?

**Comment by gvwilson** [comment]
I believe this has been resolved.
