### ISSUE TITLE
Discussion: stick with Rmd or go to pure Markdown?

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#377]
1.  We're not using RMarkdown's "execute-in-place" functionality hardly at all.
2.  Using it complicates our toolchain.
3.  If we're going to shift to plain old Markdown, now's the time (I can make the changes as I do revs).
4.  If we're not, that OK too.

Thoughts?

**Comment by lwjohnst86** [comment]
I'd say why? It doesn't really complicate the toolchain, since its only the additional Rmd to md conversion (which in the case of no code chunks basically is a rename). And changing actually would take more time away from finishing up. Combined with the fact that other books will still use this Rmd functionality.

An alternative would be to rename the files that don't use any code chunks to be md files instead. Most files that don't have code chunks are already like this.
