### ISSUE TITLE
Proposal: Map out the two semesters

### ISSUE THREAD

**Issue by DamienIrving** [merely-useful/merely-useful.github.io#56]
## Proposal

As a first step, we should map out what we want to cover in each of the two courses.

## Background

To borrow from the Teaching Tech Together section on [backward design](http://teachtogether.tech/en/process/), the first couple of steps in developing a lesson are:

1. Brainstorm to get a rough idea of what you want to cover, how you’re going to do it, what problems or misconceptions you expect to encounter, what’s not going to be included, and so on. You may also want to draw some concept maps at this stage.
2. Create or recycle learner personas (discussed in the next section) to figure out who you are trying to teach and what will appeal to them. (This step can also be done first, before the brainstorming.)
 
The learner personas seem to be coming along (https://github.com/merely-useful/merely-useful.github.io/issues/8), but as far as I'm aware we don't have a clear idea of what we want to cover in each course (and in what order).

I'd imagine we need a draft outline to hack on - probably in the form of a new `outline.Rmd` file - that might look something like the following in the first instance: 

(I've borrowed from @gvwilson's initial content in [One Extra Fact](https://merely-useful.github.io/one-extra-fact/en/) and [Still Magic](https://merely-useful.github.io/still-magic/en/) but I haven't tried to be exhaustive - it's just a conversation starter).

#### Semester 1

By the end of this course learners should be able to write code that reads, analyses and plots a dataset.

Along the way, learners will be introduced to the following concepts in either Python or R using the example datasets described in https://github.com/merely-useful/merely-useful.github.io/issues/14.

1. Introduction to the programming language (syntax, IDE)
2. Tables in Python/R
3. Data visualisation
4. Modular / reusable code
5. Version control (basics only)
6. Debugging
7. Organising projects
8. Publishing

#### Semester 2

By the end of this course learners should be able to write software that others can install/use and contribute to.

Along the way learners will be introduced to the the following concepts in Python (but not R??) using ??? datasets.

1. The Unix Shell
2. Automating Analyses
3. Unit Testing
4. Version control (more advanced)
5. Continuous Integration
6. Packaging
 
## Pros and Cons

Can't really see a downside here. I think `outline.Rmd` will evolve as we go along, but so long as we keep it up-to-date it can be the touchstone for people to refer back to when trying to figure out how the specific lesson they are working on fits into the broader course outline.

## Alternatives

Anarchy.

**Comment by gvwilson** [comment]
1.  Does "modular/reusable code" at the intro level include programming style? (I think "yes".)
2.  Do branching and pull requests go under "more advanced version control"? (I think "yes".)
3.  Does object-oriented programming (S3 or Python OOP respectively) go under "more advanced"? (I think "no" - out of scope.)
4.  I'm guessing "Organi[sz]ing projects" at the intro level is about file + directory organization; do managing issues, running a meeting, and other project management issues go in "advanced"? (I think "yes").
5.  Where does licensing go? (I think we need to talk about it as soon as people put stuff on GitHub, so novice course?)
6.  Where does inclusivity go? (I want it early because it's so important, but accept that it might fit better in the advanced material where we talk about multi-person projects - thoughts?)
8.  Do we cover refactoring? (I'd like to, but recognize we may be limited for space.)
9.  If we're talking about packaging, do we also talk about how to create configurable software? (I think "yes".)
10. I'd like to include logging, because the ops people will love us for it, but recognize it may be a topic too far - thoughts?
11. The current draft has a chapter on data syndication, mostly to show people how web applications and web APIs actually work. This is an obvious candidate to discard, but we should then show somewhere else how to read data from a web API - where will that go?
12. Where does the discussion of development process (currently `process.Rmd`) go? I think it fits into the advanced course (teamwork...) - thoughts?
