### ISSUE TITLE
Proposal: adopt outline for intermediate material in #64

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#69]
## Proposal

We should adopt the outline in #64 as a starting point for work on the intermediate book on the understanding that content will expand or be moved around as work proceeds.

## Background

#64 describes a course that covers:

- the Unix shell
- automating analyses
- creating reusable software
- advanced version control
- testing
- continuous integration
- packaging
- project management

We almost certainly *can't* cover more than this in a one-semester course, and most instructors will probably cover less (particularly if they want to include more statistics or domain-specific examples).

## Pros and Cons

**Pro:**
-   This covers many things that RSEs need to know that most data scientists don't.
-   It builds on the proposal for the novice books.

**Con:**
-   We may need to duplicate some material (one for Python, one for R).
-   People may not understand that they need this.
-   They might be right...

## Alternatives

N/A - this is a starting point for our work, and will evolve as we write.

**Comment by DamienIrving** [comment]
Passed at meeting on 29 May 2019.

**Comment by DamienIrving** [comment]
Here's the original outline we developed, with updated progress added in *italtics*.

## The Unix Shell

*First draft complete (#105)*  
*Remote access needs to be added (#157)*  
*Some of the project structure content (#160) could also be included here?*

Based on <http://swcarpentry.github.io/shell-novice/>
and <https://merely-useful.github.io/still-magic/en/shell.html>

-   How do I navigate my filesystem?
    -   moving about (cd, ls)
    -   files and directories (ls, cp, mkdir, mv, rm)
    -   paths (., .., absolute, relative, special) 
-   How do I examine and/or edit a text file?
    -   difference between text and binary files
    -   running a text editor
    -   operating on text (cat, wc, head, tail, etc)
    -   wildcards
    -   finding things (find, grep, locate)
-   How do I combine multiple commands?
    -   pipes and filters
    -   redirection to/from files
    -   loops
-   Variables
    -   define a variable
    -   use a variable
    -   what's with all the quotes?
-   Shell scripts
    -   read/write/execute file permissions
    -   `#!` lines
    -   using command-line arguments in scripts
    -   job control (&, control-c)
-   Shortcuts
    -   tab completion
    -   previous commands (up arrow, control-r)
    -   history
-   Getting help
    -   --help, man
-   Customising your shell experience
    -   .bashrc
-   Working remotely
    -   scp/rsync and ssh
    -   key pairs
-   Bonus material: non-standard commands you might find useful (tree, htop, autojump, fd, etc)

## Automating analyses

*First draft unassigned (#48).*

Based on <http://swcarpentry.github.io/make-novice/>
and <https://merely-useful.github.io/still-magic/en/automate.html>

-   How do I write a simple Makefile? 
-   How can I abbreviate the rules in my Makefiles? 
-   How can I write a Makefile to update things when my scripts have changed rather than my input files?
-   How can I define rules to operate on similar files? 
    -   Pattern rules
-   How can I eliminate redundancy in my Makefiles?
    -   Variables
    -   Functions
-   How should I document a Makefile?
-   What other tools can I use?
    -   drake for R
    -   snakemake for Python

## Reusable software

*Configuration is unassigned (#156).*  
*Documentation is unassigned (#158).*  
*Logging is no longer going to be included (#88).*

Based on <https://merely-useful.github.io/still-magic/en/configure.html>
and <https://merely-useful.github.io/still-magic/en/logging.html>

-   How do I parse the command line from within a Python script?
    -   basic structure of python scripts
    -   argparse
-   How would I implement a configuration file?
    -   as a data structure (JSON)
    -   as key/value pairs (YAML)
-   How would I report my program's progress?
    -   logging levels
    -   logging channels
    -   configuration
    -   progress bars such as tqdm
-   How do I document my programs?
    -   documentation generators
    -   docstrings in Python
    -   roxygen in R

## Version control

*First draft ready for review (#164).*  
*Need to incorporate content on branching workflows (#147).*

(The novice materials teach it with a GUI.)
Based on <http://swcarpentry.github.io/git-novice/>

-   Version control at the command line
    -   Checking progress: git status, diff, log
    -   Commit cycle: git add, commit, push, pull
-   How do I do multiple things at once?
    -   branches
    -   branch naming
    -   branch management conventions (like feature branches)
-   How do I suggest changes to other people's code?
    -   forking repositories
    -   creating pull requests
    -   reviewing pull requests

## Testing

*Testing and verification in progress (#106).*  
*Continuous integration in progress (#99).*

Based on <http://katyhuff.github.io/python-testing/>,
and <https://merely-useful.github.io/still-magic/en/unit.html>

-   Why should I test my code?
-   How do I implement tests/checks at specific points within my code?
    -   assertions (brief, this is covered in novice course)
    -   exceptions
-   How can I write and manage tests for my software?
    -   unit tests
    -   test runners
-   What tests should I write for my software?
    -   edge cases
    -   fails when it should
    -   bugs become tests
-   How can I run commands automatically every time a repository is updated?
    -   continuous integration
    -   Travis
-   How can I tell what I have and haven't tested?
    -   coverage
-   What *isn't* included?
    -   legal liabilities

## Packaging

*First draft of R packaging complete (#87).*  
*First draft Python packaging ready for review (#117).*

Based on <https://carpentrieslab.github.io/python-aos-lesson/01-conda/>
and <https://merely-useful.github.io/still-magic/en/package.html>

-   How do I install and manage my Python environment?
    -   Python distributions (Anaconda)
    -   Package managers (pip, conda)
    -   conda environments
-   How can I write a package that can be installed via pip?
-   How do I write a package that can be shared on CRAN?
-   How do version numbers work?
-   How can I put documentation for my package on the web? (e.g. Sphinx / Read The Docs for Python, pkgdown for R)

## Project management

*Managing backlog is unassigned (#148). It essentially has the issues content.*  
*Project structure has just been assigned (#160). Some it could also go earlier in the unix shell section?*  
*Inclusion is unassigned (#161).*  
*Teamwork is unassigned (#162).*

-   How can **we** keep track of who's doing what and what's still to be done?
    -   issue tracking
    -   issue tagging as lightweight workflow
-   How can **we** figure out what to build next?
    -   planning vs. agile
    -   3x3 prioritization
-   How can **we** make decisions?
    -   how to run a meeting
    -   project governance
    -   strategies for handling difficult project members

## Other topics we will include

*Publishing first draft is complete (#142).*   
*Code style and review is unassigned (#149).*  

## Other topics we might include

- SQL (#70)
- Regular expressions (#71)
- JSON (#72)
- Syndication (#145)

## Other topics we are leaving out 

-   Object-oriented programming
-   Nonstandard evaluation (in R)
-   Refactoring (#159)
-   Profiling and performance tuning
-   Time management and the effects of overwork (#163)
-   Everything with "parallel" in its name...
