### ISSUE TITLE
Discussion: should we cover JSON?

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#72]
1.  Should we cover JSON (and/or YAML) as an example of nested data?
2.  If so, should this go in the novice or intermediate material?

**Comment by ljdursi** [comment]
I think it could make a lot of sense to cover it in intermediate material, perhaps in the context of ETLing some data into structured format, not least of which because once you have JSON in your toolbox now basically every open web API is available to you.  

I would leave it out of novice because for it to make any sense you'd have to cover a lot of material, and because I think it's harder to teach in R than python (could be wrong).

**Comment by lwjohnst86** [comment]
Completely agree with with @ljdursi, I think JSON in intermediate material would be useful to know, at the least to have some mention about. As for teaching in R vs Python, I don't really know. There are several R packages to work with JSON, but not sure how "teachable" they are.

**Comment by joelostblom** [comment]
Maybe - intermediate. Depends a bit on personas... For basic usage both dplyr and pandas makes it really easy to read jsons without extensive knowledge of the format. I guess yaml. Will be talked about when we talk about markdown?

**Comment by lwjohnst86** [comment]
As per #70, leave and focus on current content. Closing and adding "on hold" label.
