### ISSUE TITLE
Proposal: adopt these learner personas

### ISSUE THREAD

**Issue by gvwilson** [merely-useful/merely-useful.github.io#8]
## Proposal

We should adopt these six learner personas to define the audience for parts 1 and 2.

## Background

We need a clear idea of who we're trying to help, what we can assume they already know, and how we're going to make their lives better. These [learner personas](http://teachtogether.tech/en/process/#s:process-personas) answer those questions by example.

## Pros and Cons

Pro:
-   Clear distinction between audiences for parts 1 and 2.
-   Part 1 covers undergraduate, faculty (who need both teaching materials and training) and non-academics.
-   Part 2 includes non-research roles.

Con:
-   Real people won't fall cleanly into one camp or the other, and our personas should reflect that.
-   May not capture the breadth of our desired audience.

## Alternatives

-   Replace or modify some or all of these personas.

## Part 1

-   **Anya** is a professor of neuropsychology who is responsible for teaching her department's introduction to statistics to 1100 first-year students every year. (Students complain that the Stats department's introductory course is too theoretical and requires more programming knowledge than they have.) When she finds time for it, her research focuses on color perception in infants.  Over the past nine years, Anya has designed and run a dozen experiments on 50-100 infant subjects each and analyzed the results using SPSS and more recently R (which she taught herself during a sabbatical). She has never taken a programming course, and suffers from impostor syndrome when talking to colleagues who are using things like GitHub and R Markdown.  Anya would like to figure out how to use R to teach her intro stats course, which currently uses a mixture of Excel and SPSS. She would like to learn more about time series analysis to support her research, and about tools like Git and R Markdown.

-   **Exton** taught business at a community college before joining a friend's startup, and now does community management for a company that builds healthcare software. He still teaches Marketing 101 every year to help people with backgrounds like his.  Exton uses Excel to keep track of who is registered for webinars, workshops, and training sessions. Some of these spreadsheets are created from CSV files produced by a web-scraping script a summer intern wrote for him a couple of years ago. Exton doesn't think of himself as a programmer, but spends hours creating complicated lookup tables in multi-sheet spreadsheets to help him figure out how many webinar attendees turn into community contributors, who answers forum posts most frequently, and so on. Exton knows there are better ways to do what he's doing, but feels overwhelmed by the flood of blog posts, tweets, and "helpful" recommendations he receives from members of the company's engineering team. He wants someone to tell him where he should start and how long it will take whatever he learns to pay off.

-   **Irwin** is 18 years old and five months into an undergraduate degree in urban planning. He's read lots of gushing articles in Wired about data science, and was excited by the prospect of learning how to do it, but dropped his CS 101 course after six weeks because nothing made sense. (His university's computer science department uses Haskell as an introductory programming language...) He is doing better in Anya's course (which he is taking as an elective), but still spends most of his time copying, pasting, and swearing.  Irwin did well in his high school math classes, and built himself a home page with HTML and CSS in a weekend workshop in grade 11. He knows how to do simple calculations in Excel, has accounts on nine different social media sites, and attends all of his morning classes online.

## Part 2

-   **Beatrice** completed a Master's in library science five years ago, and has worked since then for a small NGO. She did some statistics during her degree, and has learned some R and Python by doing data science courses online, but has no formal training in programming. Beatrice would like to tidy up the scripts, data sets, and reports she has created in order to share them with her colleagues. These lessons will show her how to do this and what "done" looks like.

-   **Jun** completed an Insight Data Science fellowship last year after doing a PhD in Geology, and now works for a company that does forensic audits. He has used a variety of machine learning and visualization software, and has made a few small contributions to a couple of open source R packages. He would now like to make his own code available to others; this guide will show him how such projects should be organized.

-   **Sami** learned a fair bit of numerical programming while doing a BSc in applied math, then started working for the university's supercomputing center. Over the past few years, the kinds of applications they are being asked to support have shifted from fluid dynamics to data analysis. This guide will teach them how to build and run data pipelines so that they can teach those skills to their users.

**Comment by ChristinaLK** [comment]
I read these and don't have any immediate comments, but will mull a bit. 

It would be helpful to add to these with what the course is going to offer each person either via a summary one-liner (the intro course will...) or as individual additions to their paragraphs.

**Comment by gvwilson** [comment]
Deferred during #7 for further work - @mbonsma and @brandeism will lead discussion.

**Comment by mbonsma** [comment]
I modified the personas for Part 1 by adding a sentence or two to each about what the book will do for them (@ChristinaLK's suggestion), and I also added two new personas to cover cases of professors or students using the book very closely for a course. New is in bold. 

## Part 1

-   **Anya** is a professor of neuropsychology who is responsible for teaching her department's introduction to statistics to 1100 first-year students every year. (Students complain that the Stats department's introductory course is too theoretical and requires more programming knowledge than they have.) When she finds time for it, her research focuses on color perception in infants.  Over the past nine years, Anya has designed and run a dozen experiments on 50-100 infant subjects each and analyzed the results using SPSS and more recently R (which she taught herself during a sabbatical). She has never taken a programming course, and suffers from impostor syndrome when talking to colleagues who are using things like GitHub and R Markdown. Anya would like to figure out how to use R to teach her intro stats course, which currently uses a mixture of Excel and SPSS. She would like to learn more about time series analysis to support her research, and about tools like Git and R Markdown. **This guide has modular lessons and exercises that she can adapt to use in her course, and it has suggestions for how to make learning interactive with a large class size. She also finds helpful instructions for applying time series analysis to data using R.**

-   **Exton** taught business at a community college before joining a friend's startup, and now does community management for a company that builds healthcare software. He still teaches Marketing 101 every year to help people with backgrounds like his. Exton uses Excel to keep track of who is registered for webinars, workshops, and training sessions. Some of these spreadsheets are created from CSV files produced by a web-scraping script a summer intern wrote for him a couple of years ago. Exton doesn't think of himself as a programmer, but spends hours creating complicated lookup tables in multi-sheet spreadsheets to help him figure out how many webinar attendees turn into community contributors, who answers forum posts most frequently, and so on. Exton knows there are better ways to do what he's doing, but feels overwhelmed by the flood of blog posts, tweets, and "helpful" recommendations he receives from members of the company's engineering team. He wants someone to tell him where he should start and how long it will take whatever he learns to pay off. **Exton finds 'Merely Useful' after some Googling, and sees an example of data analysis with spreadsheet data that looks really similar to what he's trying to do. He carefully works through that particular example, and then goes back and works through some of the earlier material in the book. He can tell that it won't take long to get this to work with his data.**

-   **Irwin** is 18 years old and five months into an undergraduate degree in urban planning. He's read lots of gushing articles in Wired about data science, and was excited by the prospect of learning how to do it, but dropped his CS 101 course after six weeks because nothing made sense. (His university's computer science department uses Haskell as an introductory programming language...) He is doing better in Anya's course (which he is taking as an elective), but still spends most of his time copying, pasting, and swearing. Irwin did well in his high school math classes, and built himself a home page with HTML and CSS in a weekend workshop in grade 11. He knows how to do simple calculations in Excel, has accounts on nine different social media sites, and attends all of his morning classes online. **Anya mentions this guide in one of her classes, and Irwin downloads the pdf to read on the bus. He loves the examples that use urban data, and right away he has tons of ideas about where to get more cool data to analyze. His urban data science blog is already taking shape in his head.**

-   **Camilla** recently started a job as an assistant professor. Her department (Medieval Studies) is trying to develop a digital humanities data-science-heavy undergraduate program, and the undergraduate chair thinks that Camilla has the most programming experience in the department and has asked her to develop an introduction to programming course for humanities students. Camilla has dabbled in natural language processing and has learned Python over the course of her previous work, but she has no experience teaching progamming and she's not sure what the best way is to teach beginners. She doesn't want to start from scratch to create a course out of nothing. She also isn't sure which programming language the new program should focus on. She finds the Merely Useful guide and feels relieved: she can pretty much use the book as-is for her course. She looks up the examples of text and image  analysis and compares how both R and Python approach those kinds of data to help her make a decision about which language to teach.

-   **Jordan** is a third-year undergraduate student in ecology. Two months ago she started working part-time for a professor in her department, and she's beginning to collect and analyze data from her own experiments with fruit flies. Her professor has asked her to learn R to do her analysis and suggested that she sign up for the introduction to quantitative data analysis in R course that the ecology department offers. The course is just starting, and it uses 'Merely Useful' as the textbook. Jordan can't wait to apply her new programming knowledge to her data, and so she starts reading ahead and trying to use her own data in some of the book's examples. As she works through examples, she realizes that she'll need to change a few things about how she records her data in spreadsheets so that it will be easier to analyze in R.

**Comment by mbonsma** [comment]
It might be useful for us to formally outline [**pathways**](https://mozillascience.github.io/working-open-workshop/personas_pathways/) for each persona beyond what I've done in the last few sentences of each persona:


1. Discovery - How do they first hear about these lessons?
2. First Contact - How do they first engage with these lessons? What medium?
3. Participation - How do they participate in or use the material?
4. Sustained Participation - How their use or involvement can continue.
5. Networked Participation - How they may network within the community.
6. Leadership (maybe not that relevant here) - How they may take on some additional responsibility on the project, or begin to lead.

**Comment by ChristinaLK** [comment]
This is helpful @mbonsma, thanks for your additions!

**Comment by mbonsma** [comment]
I won't be able to comment on this at the meeting, but after reading the results of the survey (summary in #60), I think we should **adopt these proposals without more revising** (but with the small edits I made to the Part 1 personas [here](https://github.com/merely-useful/merely-useful.github.io/issues/8#issuecomment-490260883)). 

They seem comprehensive enough to me to get us started, and I don't think we have so many that they will be cumbersome.

**Comment by gvwilson** [comment]
@gvwilson to merge
